name: Claude Code Integration

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  process-claude-request:
    runs-on: ubuntu-latest
    environment: production
    if: |
      (github.event.issue && contains(github.event.issue.labels.*.name, 'claude-code')) ||
      (github.event.comment && contains(github.event.comment.body, '@claude-code'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Claude SDK
        run: npm install @anthropic-ai/sdk @octokit/rest
      
      - name: Process Claude Code Request
        id: claude
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number || github.event.issue.number }}
          ISSUE_BODY: ${{ github.event.issue.body || github.event.comment.body }}
        run: |
          echo "Processing Claude Code request from issue #$ISSUE_NUMBER"
          echo "Checking if CLAUDE_API_KEY is available..."
          if [ -z "$CLAUDE_API_KEY" ]; then
            echo "ERROR: CLAUDE_API_KEY is not available. Please check GitHub Secrets."
            exit 1
          else
            echo "CLAUDE_API_KEY is available (length: ${#CLAUDE_API_KEY})"
          fi
          node .github/scripts/claude-integration.mjs
          
      - name: Create branch for changes
        if: success()
        run: |
          BRANCH_NAME="claude-code/issue-${{ github.event.issue.number }}-$(date +%s)"
          git checkout -b $BRANCH_NAME
          git config user.name "Claude Code Bot"
          git config user.email "claude-code[bot]@users.noreply.github.com"
          
      - name: Apply code changes
        if: success()
        run: |
          # The actual Claude Code integration would process changes here
          echo "Code changes would be applied here"
          
      - name: Commit and push changes
        if: success()
        run: |
          git add .
          git diff --staged --quiet || git commit -m "Apply Claude Code changes for issue #${{ github.event.issue.number }}"
          git push origin HEAD
          
      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: claude-code/issue-${{ github.event.issue.number }}
          title: "Claude Code: Changes for issue #${{ github.event.issue.number }}"
          body: |
            This PR contains changes generated by Claude Code for issue #${{ github.event.issue.number }}
            
            ## Changes Made
            - Automated code changes based on issue description
            
            ## Related Issue
            Closes #${{ github.event.issue.number }}
          labels: claude-code, automated